/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description 24 top-level categories with localized names.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriesResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate dataset stats
         * @description Total questions, per-language, per-source, per-category counters. Cached.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supported languages
         * @description Whitelist of `?lang=` values with native names and counts.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supported languages. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguagesResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List curated topics
         * @description 2,184 curated topics with aliases and counts.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                    q?: string;
                    kind?: "tag" | "subcategory";
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Curated topics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicsListResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topic detail with facets
         * @description Single topic + facets (byCategory, byDifficulty, byLanguage, coOccurringTags, coOccurringSubcategories) + 3 sample questions.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                };
                header?: never;
                path: {
                    /** @description Curated topic slug or alias. */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topic detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicDetailResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Topic not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List raw tags
         * @description Raw tags with display labels and counts. Threshold ≥5 questions.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                    q?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw tags. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagsListResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subcategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List raw subcategories
         * @description Raw subcategories layer. Threshold ≥5 questions.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                    q?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw subcategories. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubcategoriesListResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a problem with a question
         * @description Anonymous submission for translation / factual / inappropriate / attribution / other reports. Rate-limited 5/min/IP. No API key required.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportRequest"];
                };
            };
            responses: {
                /** @description Report accepted. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportAcceptedResponse"];
                    };
                };
                /** @description Invalid body — provide one of `questionId`, `questionText`, `questionUrl`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Question not found (when `questionId` provided). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded (5/min/IP). */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key info
         * @description Confirms your key, tier, and current rate-limit window. The first endpoint to hit when wiring a new client.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key info. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 30-day usage series
         * @description Daily request counts + summary across all your keys.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Trailing days, 1-90. */
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse questions (cursor pagination)
         * @description Paginated browse with filters and delta-sync via `updated_since`.
         */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                    /** @description ISO 8601 datetime — only questions modified after this point. */
                    updated_since?: string;
                    category?: string;
                    difficulty?: "easy" | "medium" | "hard";
                    type?: "multiple" | "boolean" | "text_input";
                    tags?: string;
                    tags_any?: string;
                    topic?: string;
                    topics_any?: string;
                    subcategory?: string;
                    quality?: "high";
                    regions?: string;
                    source?: "opentdb" | "opentriviaqa" | "mkqa" | "mmlu-prox" | "wikipedia" | "community" | "runriva" | "ai-generated" | "purchased" | "quizbase";
                    license?: "CC-BY-SA-4.0" | "CC-BY-SA-3.0" | "CC-BY-4.0" | "MIT" | "proprietary";
                    count?: "estimate" | "exact" | "none";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Questions page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionsListResponse"];
                    };
                };
                /** @description Invalid query parameters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Random questions sample
         * @description Up to 50 random questions in the requested language. Filter set identical to `/questions`.
         */
        get: {
            parameters: {
                query?: {
                    amount?: number;
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                    category?: string;
                    difficulty?: "easy" | "medium" | "hard";
                    type?: "multiple" | "boolean" | "text_input";
                    tags?: string;
                    tags_any?: string;
                    topic?: string;
                    topics_any?: string;
                    subcategory?: string;
                    quality?: "high";
                    regions?: string;
                    source?: "opentdb" | "opentriviaqa" | "mkqa" | "mmlu-prox" | "wikipedia" | "community" | "runriva" | "ai-generated" | "purchased" | "quizbase";
                    license?: "CC-BY-SA-4.0" | "CC-BY-SA-3.0" | "CC-BY-4.0" | "MIT" | "proprietary";
                    exclude?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Random sample. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionsRandomResponse"];
                    };
                };
                /** @description Invalid query parameters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single question by id
         * @description Deep link / shareable URL / moderation review.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Display language for category names + slug labels (subcategories/tags) */
                    lang?: "en" | "pl";
                };
                header?: never;
                path: {
                    /** @description UUID v7 of the question. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Question. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionByIdResponse"];
                    };
                };
                /** @description Missing, malformed, invalid, or revoked API key. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description IP not allowed (per-key allowlist). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Question not found, moderated, de-duplicated, or removed upstream. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Rate limit exceeded. See `Retry-After` header. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            /**
             * @description Absolute URL identifying the error class.
             * @example https://quizbase.runriva.com/errors/invalid_query_param
             */
            type: string;
            /** @example Invalid query parameters */
            title: string;
            /** @example 400 */
            status: number;
            /** @example lang: lang "xyz" is not supported. Supported: en, pl */
            detail: string;
            /** @example /api/v1/categories?lang=xyz */
            instance: string;
            /** @example invalid_query_param */
            code: string;
            /** @description Per-field validation errors (400 only). */
            errors?: {
                path: string;
                message: string;
            }[];
            /**
             * @description Seconds to wait before retrying (429 only).
             * @example 3600
             */
            retryAfter?: number;
            /** @description URL to upgrade plan (429 only). */
            upgradeUrl?: string;
            /**
             * @description Rate limit ceiling that was exceeded (429 only).
             * @example 5
             */
            limit?: number;
            /**
             * @description API tier whose limit was exceeded (429 only).
             * @example free
             */
            tier?: string;
            /**
             * @description Number of requests in current window (429 only).
             * @example 100
             */
            current?: number;
        };
        Question: {
            /**
             * Format: uuid
             * @example 019dd2af-1e86-7991-ae22-3dc3dc5e9b2c
             */
            id: string;
            /** @example Jaka jest stolica Polski? */
            text: string;
            /** @example Warszawa */
            correctAnswer: string;
            /**
             * @example [
             *       "Kraków",
             *       "Gdańsk",
             *       "Wrocław"
             *     ]
             */
            incorrectAnswers: string[];
            /**
             * @example multiple
             * @enum {string}
             */
            type: "multiple" | "boolean" | "text_input";
            /**
             * @example easy
             * @enum {string|null}
             */
            difficulty: "easy" | "medium" | "hard" | null;
            /** @example pl */
            language: string;
            category: components["schemas"]["CategoryRef"];
            /** @description Localized `{slug, label}` per `?lang=`. */
            subcategories: components["schemas"]["SlugLabel"][];
            /** @description Localized `{slug, label}` per `?lang=`. */
            tags: components["schemas"]["SlugLabel"][];
            /**
             * @example [
             *       "pl"
             *     ]
             */
            regions: string[];
            attribution: components["schemas"]["Attribution"];
            /**
             * Format: uuid
             * @description Direct parent (usually English source) when this is a translation.
             */
            translationOf: string | null;
            /**
             * Format: uuid
             * @description Canonical source across translation chains.
             */
            rootQuestionId: string | null;
            /**
             * @description Translation provenance. `null` for original-language records.
             * @enum {string|null}
             */
            translator: "machine" | "human" | "native" | null;
            /** @description Optional explanation of the correct answer. */
            explanation: string | null;
            /** @description Forward-compatible container for stable per-source extras. Today exposes `subcategories: string[]` (also surfaced as the typed top-level `subcategories` field). Future stable fields land here additively. */
            extensions: {
                [key: string]: unknown;
            };
            /** @example 2026-04-28T06:03:05.191Z */
            createdAt: string;
            /** @example 2026-05-01T09:16:41.496Z */
            updatedAt: string;
        };
        CategoryRef: {
            /** @example 14 */
            id: number;
            /** @example geography */
            slug: string;
            /** @example Geography */
            name: string;
        };
        SlugLabel: {
            /** @example european-capitals */
            slug: string;
            /** @example European Capitals */
            label: string;
        };
        Attribution: {
            /**
             * @description Upstream contributor or community.
             * @example OpenTDB community
             */
            author: string | null;
            /**
             * @description Source slug.
             * @example opentdb
             */
            source: string;
            /**
             * @description Effective applied license (SPDX).
             * @example CC-BY-SA-4.0
             */
            license: string;
            /**
             * @description Original upstream license version.
             * @example 4.0
             */
            licenseVersion: string | null;
            /** @example https://creativecommons.org/licenses/by-sa/4.0/ */
            licenseUrl: string | null;
            /**
             * @description Original upstream id.
             * @example opentdb:17243
             */
            sourceId: string;
            /**
             * @description Link to upstream record.
             * @example https://opentdb.com/
             */
            url: string | null;
            /**
             * @description Our modifications per BY-SA § 3(a)(1)(B). e.g. `translated_pl`, `refined_text`, `quizified`.
             * @example [
             *       "translated_pl"
             *     ]
             */
            modifications: string[];
            /**
             * @description ISO timestamp of our last modification.
             * @example 2026-05-01T09:16:41.496Z
             */
            lastModified: string;
        };
        CategoriesResponse: {
            data: components["schemas"]["CategoryEntry"][];
            meta: components["schemas"]["MetaCategories"];
        };
        CategoryEntry: {
            /** @example 14 */
            id: number;
            /** @example geography */
            slug: string;
            /** @example Geografia */
            name: string;
            /** @example 22 */
            opentdbId: number | null;
            /** @example null */
            parentId: number | null;
        };
        MetaCategories: {
            /** @example 24 */
            count: number;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        StatsResponse: {
            /** @example 1294009 */
            total: number;
            /**
             * @example {
             *       "en": 646194,
             *       "pl": 647815
             *     }
             */
            byLanguage: {
                [key: string]: number;
            };
            /**
             * @description Counts per source slug. Pre-launch may be empty (`{}`) — snapshot pipeline gap.
             * @example {}
             */
            bySource: {
                [key: string]: number;
            };
            byCategory: components["schemas"]["StatsCategoryEntry"][];
            byDifficulty: components["schemas"]["StatsByDifficulty"];
            byTopic: components["schemas"]["StatsTopicEntry"][];
            byTag: components["schemas"]["StatsTagEntry"][];
            meta: components["schemas"]["MetaStats"];
        };
        StatsCategoryEntry: {
            /** @example geography */
            slug: string;
            /** @example geography */
            name: string;
            /** @example 146384 */
            count: number;
        };
        /** @description Difficulty distribution. Pre-launch zero-filled — snapshot pipeline gap. */
        StatsByDifficulty: {
            /** @example 0 */
            easy: number;
            /** @example 0 */
            medium: number;
            /** @example 0 */
            hard: number;
            /** @example 0 */
            unrated: number;
        };
        StatsTopicEntry: {
            /** @example biography */
            slug: string;
            /** @example Biographies */
            label: string;
            /** @example 245103 */
            count: number;
        };
        StatsTagEntry: {
            /** @example united-states */
            slug: string;
            /** @example United States */
            label: string;
            /** @example 15281 */
            count: number;
        };
        MetaStats: {
            /** @example 2026-05-05T16:32:09.001Z */
            generatedAt: string;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        LanguagesResponse: {
            data: components["schemas"]["LanguageEntry"][];
            meta: components["schemas"]["MetaLanguages"];
        };
        LanguageEntry: {
            /** @example pl */
            code: string;
            /** @example Polish */
            name: string;
            /** @example Polski */
            nativeName: string;
            /** @example 647599 */
            count: number;
        };
        MetaLanguages: {
            /** @example 2 */
            count: number;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        TopicsListResponse: {
            data: components["schemas"]["TopicEntry"][];
            meta: components["schemas"]["MetaTopicsList"];
            _links?: components["schemas"]["Links"];
        };
        TopicEntry: {
            /** @example biography */
            slug: string;
            /**
             * @example subcategory
             * @enum {string}
             */
            kind: "tag" | "subcategory";
            /** @example Biography */
            label: string;
            /**
             * @example [
             *       "biography",
             *       "biographies"
             *     ]
             */
            aliases: string[];
            /** @example 64977 */
            count: number;
        };
        MetaTopicsList: {
            /** @example 100 */
            count: number;
            /** @example 2184 */
            total: number;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        Links: {
            /** @description URL to the next page. */
            next?: string;
            /** @description URL to the previous page. */
            prev?: string;
        };
        TopicDetailResponse: {
            topic: components["schemas"]["TopicEntry"];
            facets: components["schemas"]["TopicFacets"];
            samples: components["schemas"]["TopicSampleQuestion"][];
            meta: components["schemas"]["MetaBasic"];
        };
        TopicFacets: {
            byCategory: {
                slug: string;
                name: string;
                count: number;
            }[];
            byDifficulty: {
                [key: string]: number;
            };
            byLanguage: {
                [key: string]: number;
            };
            coOccurringTags: components["schemas"]["StatsTagEntry"][];
            coOccurringSubcategories: components["schemas"]["StatsTagEntry"][];
        };
        TopicSampleQuestion: {
            /** Format: uuid */
            id: string;
            text: string;
            /** @enum {string} */
            type: "multiple" | "boolean" | "text_input";
            /** @enum {string|null} */
            difficulty: "easy" | "medium" | "hard" | null;
            language: string;
        };
        MetaBasic: {
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        TagsListResponse: {
            data: components["schemas"]["RawSlugEntry"][];
            meta: components["schemas"]["MetaTagsList"];
            _links?: components["schemas"]["Links"];
        };
        RawSlugEntry: {
            /** @example united-states */
            slug: string;
            /** @example United States */
            label: string;
            /** @example 7673 */
            count: number;
        };
        MetaTagsList: {
            /** @example 100 */
            count: number;
            /** @example 87559 */
            total: number;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        SubcategoriesListResponse: {
            data: components["schemas"]["RawSlugEntry"][];
            meta: components["schemas"]["MetaTagsList"];
            _links?: components["schemas"]["Links"];
        };
        ReportAcceptedResponse: {
            /** @enum {boolean} */
            received: true;
            /**
             * Format: uuid
             * @example 019df4c5-1234-7abc-9def-0123456789ab
             */
            reportId: string;
            meta: components["schemas"]["MetaReport"];
        };
        MetaReport: {
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        ReportRequest: {
            /**
             * Format: uuid
             * @description UUID of the question being reported.
             */
            questionId?: string;
            /** @description Question text if no ID available. */
            questionText?: string;
            /**
             * Format: uri
             * @description Public URL where the question was seen.
             */
            questionUrl?: string;
            /**
             * @example translation
             * @enum {string}
             */
            type: "translation" | "factual" | "inappropriate" | "attribution" | "other";
            /** @description What is wrong, in your own words. */
            comment?: string;
            /**
             * Format: email
             * @description Optional follow-up address.
             */
            reporterEmail?: string;
        };
        MeResponse: {
            key: components["schemas"]["ApiKeyInfo"];
            /**
             * @example free
             * @enum {string}
             */
            tier: "free" | "indie" | "pro" | "enterprise";
            rateLimit: components["schemas"]["RateLimitInfo"];
            monthlyQuota: components["schemas"]["MonthlyQuota"];
            meta: components["schemas"]["MetaMe"];
        };
        ApiKeyInfo: {
            /** @example 01J3KXY1ZAB7CQNR8TP4Z9EXMQ */
            id: string;
            /** @example Default key */
            name: string;
            /**
             * @description Masked display value.
             * @example qb_pk_••••1234
             */
            prefix: string;
            /**
             * @description `pk` (publishable, CORS-safe for browsers) or `sk` (secret, backend-only).
             * @example pk
             * @enum {string}
             */
            scope: "pk" | "sk";
        };
        RateLimitInfo: {
            /**
             * @description Burst window cap (10s sliding). Shared across all active keys of the user.
             * @example 10
             */
            limit: number;
            /** @example 8 */
            remaining: number;
            /** @example 7 */
            resetInSeconds: number;
            /** @example 10 */
            burstPer10s: number;
            /** @example 500 */
            perDay: number;
        };
        MonthlyQuota: {
            /** @example null */
            limit: number | null;
            /** @example 0 */
            used: number;
            /** @example null */
            resetsAt: string | null;
        };
        MetaMe: {
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        UsageResponse: {
            summary: components["schemas"]["UsageSummary"];
            series: components["schemas"]["UsageDayPoint"][];
            meta: components["schemas"]["MetaUsage"];
        };
        UsageSummary: {
            /** @enum {string} */
            tier: "free" | "indie" | "pro" | "enterprise";
            today: components["schemas"]["UsageWindow"];
            week: components["schemas"]["UsageWindow"];
            month: components["schemas"]["UsageWindow"];
        };
        UsageWindow: {
            /** @example 142 */
            count: number;
            /** @example 87 */
            prev: number;
            /**
             * @description Percentage change vs previous equivalent window.
             * @example 63
             */
            delta: number | null;
            /** @example 500 */
            limit: number | null;
            /** @example 2026-05-04 */
            windowStart: string;
            /** @example 2026-05-04 */
            windowEnd: string;
        };
        UsageDayPoint: {
            /** @example 2026-04-28 */
            day: string;
            /** @example 87 */
            requests: number;
            /**
             * @description 5xx count (server-side).
             * @example 0
             */
            errors: number;
            /**
             * @description 4xx count (caller-side: 401/429/400/422).
             * @example 2
             */
            clientErrors: number;
        };
        MetaUsage: {
            /** @example 2026-04-28 */
            from: string;
            /** @example 2026-05-04 */
            to: string;
            /** @example 7 */
            days: number;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        QuestionsListResponse: {
            data: components["schemas"]["Question"][];
            meta: components["schemas"]["MetaPaginated"];
            _links?: components["schemas"]["Links"];
        };
        MetaPaginated: {
            /**
             * @description Items on this page.
             * @example 50
             */
            count: number;
            /**
             * @description Total matching items (when `count=exact`).
             * @example 1294009
             */
            total?: number;
            /**
             * @description Planner-estimated total (default `count=estimate`).
             * @example 545379
             */
            totalEstimate?: number;
            /**
             * @description Echo of the `count` query param.
             * @example estimate
             * @enum {string}
             */
            countMode?: "estimate" | "exact" | "none";
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        QuestionsRandomResponse: {
            data: components["schemas"]["Question"][];
            meta: components["schemas"]["MetaRandom"];
        };
        MetaRandom: {
            /** @example 5 */
            count: number;
            /**
             * @description Language of the response content.
             * @example en
             */
            language: string;
            /**
             * Format: uuid
             * @description Unique request identifier (also in `X-Request-Id` response header).
             * @example 127fc6d1-d6fb-4771-b2a7-211a08749e5b
             */
            requestId: string;
        };
        QuestionByIdResponse: {
            data: components["schemas"]["Question"];
            meta: components["schemas"]["MetaBasic"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
